### ISSUE TITLE
Two Content Types

### ISSUE THREAD

**Issue by WORMSS** [jshttp/media-typer#7] opened 2017-05-18 15:41 UTC
This was more of an **"info"** for anyone who may come across this in the future.  

A guy on the [express gitter](https://gitter.im/expressjs/express) was trying to work out why `body-parser.json()` was not parsing his data.  
What looked suspicious to me was his content-type being a double `application/json`.  
Looked like the certain fetch library he was using was doing it.  
```header
Content-Type:  application/json, application/json
```
After digging and digging, via `body-parser`, `type-is` and finally `media-typer` I found it was a regular expression that was causing it to fail.  
Read the [rfc7231](https://tools.ietf.org/html/rfc7231#appendix-D) from a link in another issue to find that **two content types is not valid**.  
It makes sense, but until you actually KNOW it, you can never certain.  

Just wanted to leave this hear in case someone else came along with something similar.  

I didn't know if there was any sanity checking that could be done?

**Comment by dougwilson** [comment] 2017-05-18 15:44
Closing this since it's not an issue. When you pass this module an invalid type, it throws an error that it is invalid, thus already accounting for your concern about sanity checking (you know there is an issue parsing since an error is thrown).

**Closed by dougwilson** 2017-05-18 15:44 UTC

**Comment by WORMSS** [comment] 2017-05-18 15:45
But then type-is swallows the error, so the end user who is using express doesn't see it.

**Comment by dougwilson** [comment] 2017-05-18 15:52
So what change are you expecting this module to make (since this is where you filed the issue)?

**Comment by WORMSS** [comment] 2017-05-18 15:57
None, I asked a question, 
I did state on the very first line that this was more for **info** for anyone else encountering this.
So someone can hopefully come across this via a google search and know how to fix it rather than have to dig and dig and dig to see why it was failing.
If it happened once, it may happen again.
Just trying to help future people.
I could have posted it on Express or BodyParser since that is what people are interacting with, but since this was the end of the line for tracking down the problem @lion19 was having, I thought this be the sanest place.

**Comment by dougwilson** [comment] 2017-05-18 16:00
Gotcha. I guess I was confused because issue trackers are for tracking issues in a library. Nothing you posted to me sounded like an issue in this library. Perhaps StackOverflow is a more appropriate place to post?

**Comment by WORMSS** [comment] 2017-05-18 16:06
If he had posted an issue on StackOverflow I could have answered it.. Though sadly I have not trulled through StackOverflow to help people in a while.
I just help the people I can who are stuck via Gitter in the Express Channel.
It's why I keep popping up on all your repos. You sure are a busy little bee. 🐝

**Comment by dougwilson** [comment] 2017-05-18 16:07
If the action item you're trying to achieve as well is to inform users, perhaps the action item for the issue is to improve the module's documentation? Any suggestions?

**Comment by WORMSS** [comment] 2017-05-18 16:17
I think for this particular issue, was more for someone to know that the header he supplied was "off spec".
But I cannot think of how to convey this. Can't even use console.log/warn/debug since quite a few people build their projects directly on Heroku which doesn't allow much in the way of viewing console logs.. 
Sadly besides making something easy to spot via a google search, I am at a bit of a loss. 

Maybe a possible "Trouble Shooting" checklist on `body-parser` / `express` on reasons why something doesn't parse as expected.. Since they are the popular libraries.

**Comment by dougwilson** [comment] 2017-05-18 18:26
Yea, that makes sense. A lot of times, it's hard for me to think of adding something to docs that are just an obvious thing so I don't even think about it. I understand that it's not obvious for everyone, and not knowing is not a failure, but it makes it difficult for me to write docs like troubleshooting without actually having an understanding of how a user would approach the issue from not knowing. This means that I really do rely on users helping by providing docs (could be a PR, could even be what they think would be right, but as an issue if they are not comfortable with a PR) so I can incorporate and help others.

For example, I never realized that "Can't even use console.log/warn/debug since quite a few people build their projects directly on Heroku which doesn't allow much in the way of viewing console logs.." since I deploy to Heroku daily and have never had an issue viewing these. Perhaps I'm in the minority here, but it's hard for me to understand what method is the most accessible to everyone, so any suggested docs / wording is super helpful :) !
